# Generated by Django 4.2.30 on 2026-05-25 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=10)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct emissions'), (2, 'Scope 2 — Purchased electricity'), (3, 'Scope 3 — Value chain')])),
                ('category', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('electricity', 'Purchased Electricity'), ('flight', 'Air Travel'), ('hotel', 'Hotel Stay'), ('car_rental', 'Car Rental'), ('rail', 'Rail Travel'), ('procurement', 'Procurement')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(help_text='e.g. liters, kWh, km, nights', max_length=20)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_canonical', models.CharField(help_text='liters | kWh | km | nights', max_length=20)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('emission_factor_source', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('location_ref', models.CharField(blank=True, default='', help_text='Plant code, meter ID, airport pair — source-specific identifier', max_length=255)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('locked', 'Locked for Audit')], default='pending', max_length=10)),
                ('flag_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='organizations.organization')),
                ('raw_record', models.OneToOneField(blank=True, help_text='Null only for manually entered records', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_record', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', 'organization'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('field_edit', 'Field Edit'), ('ingested', 'Record Ingested')], max_length=20)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('from_value', models.TextField(blank=True, default='')),
                ('to_value', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='emissions.activityrecord')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
